name = "Conselho dos Cimios"
author = "cauazingcf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfdff52eedd1a1660b00c7de5edef7fe2145960b7a3e8757c54668838b71e8fe"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
