name = "Conselho dos Cimios"
author = "cauazingcf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68016d2b61c7806dea5dfcf22a8e8a35c2945918c01c2d616f10680bfe12cabd"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
