name = "Conselho dos Cimios"
author = "cauazingcf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e17d54eb7450bbca24e0f2aa26e062f89baf17274f52dfa17e23ad1c55d7bbcb"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
