[debug]
	# Nome: Modo depuração
	# Descrição: Ativa o modo depuração
	# Valores válidos: [true, false]
	# Valor padrão: false
	debugMode = false

	# Nome: Depuração de GUIs
	# Descrição: Ativa modo de depuração de interfaces
	# Valores válidos: [true, false]
	# Valor padrão: false
	debugGuis = false

	# Nome: Depuração de entradas
	# Descrição: Ativa modo de depuração de entradas
	# Valores válidos: [true, false]
	# Valor padrão: false
	debugInputs = false

	# Nome: Dicas com info de depuração
	# Descrição: Adiciona informações de depuração nas dicas quando dicas avançadas estão ativadas.
	# Valores válidos: [true, false]
	# Valor padrão: false
	debugInfoTooltipsEnabled = false

	# Nome: Ativar itens de teste que causam crash
	# Descrição: Adiciona ingredientes que crasham de propósito para depurar o JEI.
	# Valores válidos: [true, false]
	# Valor padrão: false
	crashingTestItemsEnabled = false

	# Nome: jei.config.debug.debug.crashingTestRecipesEnabled
	# Descrição: jei.config.debug.debug.crashingTestRecipesEnabled.description
	# Valores válidos: [true, false]
	# Valor padrão: false
	crashingTestRecipesEnabled = false

	# Nome: Registrar estatísticas da árvore de sufixos
	# Descrição: Registra informações sobre as árvores de sufixos usadas na busca.
	# Valores válidos: [true, false]
	# Valor padrão: false
	logSuffixTreeStats = false


